[package]
name = "madm"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A minimal, Git-native dotfiles manager"
license = "MIT"
repository = "https://github.com/sbatten/madm"
homepage = "https://sbatten.github.io/madm/"

[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
